import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black h-screen text-white flex items-center justify-center">
        <h1 className="text-2xl"> Zopa vps </h1>
      </main>
    </>
  );
};

export default Home;
